spring:
  mail:
    #邮箱服务器地址
    host: smtp.qq.com
    username: hulang6666@qq.com
    password: swotmgwsftrmjegb
    default-encoding: UTF-8

mail:
  #以谁来发送邮件
  fromMail:
    addr: hulang6666@qq.com
